Repository ChromeGaming/Spaceship-escort, pull requests merged in 2024-05, with the labels that each got.

#12 sepearte the script, style and html file
  index.html
  script.js
  style.css
Labels: GSSoC'24, Level - 1

#36 Fixed Issue : placed image fetched from locally under img
  img/spaceships.png
  index.html
  style.css
Labels: gssoc, level2, Approved

#37 Enhance ReadMe file
  README.md
Labels: gssoc, level1, Approved

#38 fixed pause/play bug
  index.html
  script.js
Labels: gssoc, level2, Approved

#47 Issue#21 change weapon icon
  img/SPRTshipsicons.png
  style.css
Labels: gssoc, level2, Approved

#54 [New Feature]: Would u like to add a rocket preloader?
  index.html
  rocket.gif
Labels: enhancement, gssoc, level2

#69 Added home Button
  index.html
  style.css
Labels: enhancement, gssoc, level2

#65 [Bug]: Button not Accessible fixed
  index.html
Labels: bug, gssoc, level1

#64 Create LEARN.md
  LEARN.md
Labels: documentation, gssoc, level1

#70 Home icon
  img/home-button-svgrepo-com.svg
  index.html
  style.css
Labels: gssoc, level1, Approved
