Repository ChromeGaming/Spaceship-escort, pull requests merged in 2024-06, with the labels that each got.

#80 404 not found page added
  404.html
  img/404.png
Labels: gssoc, level2, Approved

#20 Fixed Issue#17
  index.html
  script.js
  style.css
Labels: enhancement, gssoc, level2

#106 Deleted repeated and colliding code
  .vscode/settings.json
  index.html
Labels: gssoc, level1

#78 change cursor to pointer
  index.html
Labels: gssoc, level2
